In [1]:
import pandas as pd

pd.set_option('display.max_rows', None)

alunos_df = pd.read_csv("C:/Users/pedro/Downloads/TRI/microdados_enem_2022/DADOS/MICRODADOS_ENEM_2022.csv", nrows= 6 * 1000 * 1000, sep=";",  encoding='latin')
#alunos_df = pd.read_csv("C:/Users/pedro/Downloads/TRI/microdados_enem_2022/DADOS/LLM_ENEM_2022.csv", nrows= 6 * 1000 * 1000, sep=";",  encoding='latin')


alunos_df = alunos_df.dropna(subset=['TX_GABARITO_CH'])
alunos_df = alunos_df.dropna(subset=['TX_GABARITO_MT'])

alunos_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2344823 entries, 2 to 3476102
Data columns (total 76 columns):
 #   Column                  Dtype
---  ------                  -----
 0   NU_INSCRICAO            int64
 1   NU_ANO                  int64
 2   TP_FAIXA_ETARIA         int64
 3   TP_SEXO                 object
 4   TP_ESTADO_CIVIL         int64
 5   TP_COR_RACA             int64
 6   TP_NACIONALIDADE        int64
 7   TP_ST_CONCLUSAO         int64
 8   TP_ANO_CONCLUIU         int64
 9   TP_ESCOLA               int64
 10  TP_ENSINO               float64
 11  IN_TREINEIRO            int64
 12  CO_MUNICIPIO_ESC        float64
 13  NO_MUNICIPIO_ESC        object
 14  CO_UF_ESC               float64
 15  SG_UF_ESC               object
 16  TP_DEPENDENCIA_ADM_ESC  float64
 17  TP_LOCALIZACAO_ESC      float64
 18  TP_SIT_FUNC_ESC         float64
 19  CO_MUNICIPIO_PROVA      int64
 20  NO_MUNICIPIO_PROVA      object
 21  CO_UF_PROVA             int64
 22  SG_UF_PROVA             object
 23  TP_PRESENCA_CN          int64
 24  TP_PRESENCA_CH          int64
 25  TP_PRESENCA_LC          int64
 26  TP_PRESENCA_MT          int64
 27  CO_PROVA_CN             float64
 28  CO_PROVA_CH             float64
 29  CO_PROVA_LC             float64
 30  CO_PROVA_MT             float64
 31  NU_NOTA_CN              float64
 32  NU_NOTA_CH              float64
 33  NU_NOTA_LC              float64
 34  NU_NOTA_MT              float64
 35  TX_RESPOSTAS_CN         object
 36  TX_RESPOSTAS_CH         object
 37  TX_RESPOSTAS_LC         object
 38  TX_RESPOSTAS_MT         object
 39  TP_LINGUA               int64
 40  TX_GABARITO_CN          object
 41  TX_GABARITO_CH          object
 42  TX_GABARITO_LC          object
 43  TX_GABARITO_MT          object
 44  TP_STATUS_REDACAO       float64
 45  NU_NOTA_COMP1           float64
 46  NU_NOTA_COMP2           float64
 47  NU_NOTA_COMP3           float64
 48  NU_NOTA_COMP4           float64
 49  NU_NOTA_COMP5           float64
 50  NU_NOTA_REDACAO         float64
 51  Q001                    object
 52  Q002                    object
 53  Q003                    object
 54  Q004                    object
 55  Q005                    int64
 56  Q006                    object
 57  Q007                    object
 58  Q008                    object
 59  Q009                    object
 60  Q010                    object
 61  Q011                    object
 62  Q012                    object
 63  Q013                    object
 64  Q014                    object
 65  Q015                    object
 66  Q016                    object
 67  Q017                    object
 68  Q018                    object
 69  Q019                    object
 70  Q020                    object
 71  Q021                    object
 72  Q022                    object
 73  Q023                    object
 74  Q024                    object
 75  Q025                    object
dtypes: float64(21), int64(18), object(37)
memory usage: 1.3+ GB

In [2]:
def grade_CTT(row, tipo_prova):
  
    student_responses =  [char for char in row['TX_RESPOSTAS_' + tipo_prova]] 
    correct_responses = [char for char in row['TX_GABARITO_' + tipo_prova]]
   
    # Verifique se os vetores têm o mesmo comprimento
    if len(student_responses) != len(correct_responses):
        return "Os vetores têm comprimentos diferentes"
    
    # Inicialize a contagem de respostas corretas
    correct_count = 0
    
    # Percorra os vetores e conte as respostas corretas
    for i in range(len(student_responses)):
        if student_responses[i] == correct_responses[i]:
            correct_count += 1
    
    return correct_count

# Exemplo de uso da função:
#student_answers = "AAAABCCC"
#correct_answers = "AAAABBBB"

#num_correct = grade_CTT(student_answers, correct_answers)
#print("Número de respostas corretas:", num_correct)

In [3]:
alunos_df['CO_PROVA_CH'].value_counts()

CO_PROVA_CH
1057.0    584266
1055.0    576449
1058.0    576412
1056.0    575951
1178.0      7479
1177.0      7400
1176.0      7346
1175.0      7332
1063.0       928
1062.0       335
1136.0       242
1135.0       239
1137.0       233
1138.0       211
Name: count, dtype: int64

In [4]:
def response_pattern(row, tipo_prova):

    response_pattern = ""
    student_responses =  [char for char in row['TX_RESPOSTAS_' + tipo_prova]] 
    correct_responses = [char for char in row['TX_GABARITO_' + tipo_prova]]
   
    # Verifique se os vetores têm o mesmo comprimento
    if len(student_responses) != len(correct_responses):
        return "Os vetores têm comprimentos diferentes"
    
    # Inicialize a contagem de respostas corretas
    correct_count = 0
    
    # Percorra os vetores e conte as respostas corretas
    for i in range(len(student_responses)):
        if student_responses[i] == correct_responses[i]:
            response_pattern += "1"
        else:       
            response_pattern += "0"
    return response_pattern

# Exemplo de uso da função:
#student_answers = "AAAABCCC"
#correct_answers = "AAAABBBB"

#num_correct = grade_CTT(student_answers, correct_answers)
#print("Número de respostas corretas:", num_correct)

In [5]:
alunos_df['CTT_SCORE_CH'] = alunos_df.apply(grade_CTT, axis=1,  args=('CH',))
alunos_df['RESPONSE_PATTERN_CH'] = alunos_df.apply(response_pattern, axis=1, args=('CH',))

alunos_df['CTT_SCORE_MT'] = alunos_df.apply(grade_CTT, axis=1,  args=('MT',))
alunos_df['RESPONSE_PATTERN_MT'] = alunos_df.apply(response_pattern, axis=1, args=('MT',))

In [6]:
alunos_df[['TX_RESPOSTAS_CH','TX_GABARITO_CH', 'CTT_SCORE_CH', 'CO_PROVA_CH', 'RESPONSE_PATTERN_CH']].sort_values(by='CTT_SCORE_CH', ascending=False).head(20)

,TX_RESPOSTAS_CH,TX_GABARITO_CH,CTT_SCORE_CH,CO_PROVA_CH,RESPONSE_PATTERN_CH
1229474,DEABEEDAEBAAECBECBABCDDAAADBCEDAEACDBBCDCBECA,DEABEEDAEBAAECBECBABCDDAAADBCEDAEACDBBCDCBECA,45,1055.0,111111111111111111111111111111111111111111111
1637150,ECBABCDDAAECBCBECAEBAEACDEEDABBCDDEABCEDAAADB,ECBABCDDAAECBCBECAEBAEACDEEDABBCDDEABCEDAAADB,45,1056.0,111111111111111111111111111111111111111111111
293208,DEABEEDAEBAAECBECBABCDDAAADBCEDAEACDBBCDCBECA,DEABEEDAEBAAECBECBABCDDAAADBCEDAEACDBBCDCBECA,45,1055.0,111111111111111111111111111111111111111111111
1547504,ECBABCDDAAECBCBECAEBAEACDEEDABBCDDAABCEDAAADB,ECBABCDDAAECBCBECAEBAEACDEEDABBCDDEABCEDAAADB,44,1056.0,111111111111111111111111111111111101111111111
2151489,CEDAAADBAECBCDDADEABCBECAEEDAEBABBCDECEABEACD,CEDAAADBAECBCDDADEABCBECAEEDAEBABBCDECBABEACD,44,1058.0,111111111111111111111111111111111111110111111
2234509,CBECACBCDEACDCEDAAADBCDDAECBABAECBEBAEEDADEAB,CBECABBCDEACDCEDAAADBCDDAECBABAECBEBAEEDADEAB,44,1057.0,111110111111111111111111111111111111111111111
1986556,CEDAAADBAECBCDDADEABCBECAEEDAEBABBCDECBABEADD,CEDAAADBAECBCDDADEABCBECAEEDAEBABBCDECBABEACD,44,1058.0,111111111111111111111111111111111111111111101
709510,CEDAAADBAECBCDDADEABCBECAEEDADBABBCDECBABEACD,CEDAAADBAECBCDDADEABCBECAEEDAEBABBCDECBABEACD,44,1058.0,111111111111111111111111111110111111111111111
1318260,DEABEEDADBAAECBECBABCDDAAADBCEDAEACDBBCDCBECA,DEABEEDAEBAAECBECBABCDDAAADBCEDAEACDBBCDCBECA,44,1055.0,111111110111111111111111111111111111111111111
1921380,ACCCEECACEDABCABEDCCABBADBDCCBDAEACBBBEDBADBA,ACCCEECACEDABCABBDCCABBADBDCCBDAEACBBBEDBADBA,44,1137.0,111111111111111101111111111111111111111111111
2876574,DEABEEDAEBAAECBECBABCDDAAADBDEDAEACDBBCDCBECA,DEABEEDAEBAAECBECBABCDDAAADBCEDAEACDBBCDCBECA,44,1055.0,111111111111111111111111111101111111111111111
3186373,DEABEEDAEBAAECBECAABCDDAAADBCEDAEACDBBCDCBECA,DEABEEDAEBAAECBECBABCDDAAADBCEDAEACDBBCDCBECA,44,1055.0,111111111111111110111111111111111111111111111
1933447,ECEABCDDAAECBCBECAEBAEACDEEDABBCDDEABCEDAAADB,ECBABCDDAAECBCBECAEBAEACDEEDABBCDDEABCEDAAADB,44,1056.0,110111111111111111111111111111111111111111111
2570749,CEDAAADBAECBCDDADEABCAECAEEDAEBABBCDECBABEACD,CEDAAADBAECBCDDADEABCBECAEEDAEBABBCDECBABEACD,44,1058.0,111111111111111111111011111111111111111111111
700967,DEABEEDAEBAAECBECBABCDDAAADBCEDAEACDBBCDCBBCA,DEABEEDAEBAAECBECBABCDDAAADBCEDAEACDBBCDCBECA,44,1055.0,111111111111111111111111111111111111111111011
1874497,ECBABCDDAEECBCBECAEBAEACDEEDABBCDDEABCEDAAADB,ECBABCDDAAECBCBECAEBAEACDEEDABBCDDEABCEDAAADB,44,1056.0,111111111011111111111111111111111111111111111
2045462,CBECABBCDEACDCECAAADBCDDAECBABAECBEBAEEDADEAB,CBECABBCDEACDCEDAAADBCDDAECBABAECBEBAEEDADEAB,44,1057.0,111111111111111011111111111111111111111111111
393497,CBECABBCDEACDCEDAAADBCDDAECBABAECBEBACEDADEAB,CBECABBCDEACDCEDAAADBCDDAECBABAECBEBAEEDADEAB,44,1057.0,111111111111111111111111111111111111101111111
297067,DEABEEDADBAAECBECBABCDDAAADBCEDAEACDBBCDCBECA,DEABEEDAEBAAECBECBABCDDAAADBCEDAEACDBBCDCBECA,44,1055.0,111111110111111111111111111111111111111111111
1832817,DEABEEDAEBAAECBECBABCDDAAADBCEDAEACDBBCDCBBCA,DEABEEDAEBAAECBECBABCDDAAADBCEDAEACDBBCDCBECA,44,1055.0,111111111111111111111111111111111111111111011

In [7]:
column_names = {'TX_RESPOSTAS_MT': 'TX_RESPOSTAS', 'TX_GABARITO_MT': 'TX_GABARITO', 'NU_NOTA_MT': 'NU_NOTA', 'CTT_SCORE_MT': 'CTT_SCORE', 'CO_PROVA_MT': 'CO_PROVA',  'RESPONSE_PATTERN_MT': 'RESPONSE_PATTERN'}

alunos_df[['TX_RESPOSTAS_MT','TX_GABARITO_MT', 'NU_NOTA_MT', 'CTT_SCORE_MT', 'CO_PROVA_MT', 'RESPONSE_PATTERN_MT']] \
 .sort_values(by='NU_NOTA_MT', ascending=False) \
 .rename(columns={'TX_RESPOSTAS_MT': 'TX_RESPOSTAS', 'TX_GABARITO_MT': 'TX_GABARITO', 'NU_NOTA_MT': 'NU_NOTA', 'CTT_SCORE_MT': 'CTT_SCORE', 'CO_PROVA_MT': 'CO_PROVA',  'RESPONSE_PATTERN_MT': 'RESPONSE_PATTERN'}) \
 .to_csv("test_responses_humans/test_responses_humans_MT.csv")

alunos_df[['TX_RESPOSTAS_CH','TX_GABARITO_CH', 'NU_NOTA_CH', 'CTT_SCORE_CH', 'CO_PROVA_CH', 'RESPONSE_PATTERN_CH']] \
 .sort_values(by='NU_NOTA_CH', ascending=False) \
 .rename(columns={'TX_RESPOSTAS_CH': 'TX_RESPOSTAS', 'TX_GABARITO_CH': 'TX_GABARITO', 'NU_NOTA_CH': 'NU_NOTA', 'CTT_SCORE_CH': 'CTT_SCORE', 'CO_PROVA_CH': 'CO_PROVA',  'RESPONSE_PATTERN_CH': 'RESPONSE_PATTERN'}) \
 .to_csv("test_responses_humans/test_responses_humans_CH.csv")

In [9]:
import pandas as pd
from scipy.stats import entropy

def generate_human_histogram_df(responses_df, PROVA, CO_PROVA, o):

    itens_df = pd.read_csv("c:/Users/pedro/Downloads/TRI/microdados_enem_2022/DADOS/ITENS_PROVA_2022.csv", sep=';', encoding = "latin")
    itens_df = itens_df[itens_df['CO_PROVA'] == CO_PROVA].sort_values(by='CO_POSICAO', ascending=True)
    itens_df.reset_index()
    itens_df['human_item_id'] = range(1, len(itens_df) + 1)

    print('len_itens_df', len(itens_df))

    options =  ['A', 'B', 'C', 'D', 'E']
    
    histograms_options = {}
    histograms_correct = { }
    correct_options = list()
    correct_response_pattern = ""
    
    for index, student in responses_df.iterrows():      
        if student['TP_PRESENCA_' + PROVA] != 1:
            continue  
            
        for item_id, choice_original_order in enumerate(student['TX_RESPOSTAS_' + PROVA], start=1):

            co_prova = student['CO_PROVA_'+PROVA]
            if co_prova != CO_PROVA:
                continue
            
            #shuffled_response_pattern = item['SHUFFLED_ORDER_TX_RESPOSTAS']
            response_pattern = student['TX_RESPOSTAS_' + PROVA]
            #shuffled_correct_response_pattern = item['SHUFFLED_ORDER_TX_GABARITO']
            correct_response_pattern = student['TX_GABARITO_'+  PROVA]
        
            #choice_shuffled_order = shuffled_response_pattern[item_id-1]
            #correct_shuffled_order = shuffled_correct_response_pattern[item_id-1]

            choice_original_order = response_pattern[item_id-1]
            correct_original_order = correct_response_pattern[item_id-1]
        
            correct = choice_original_order == correct_original_order

            # Update the histogram for the current position and letter
            if item_id not in histograms_options:
                histograms_options[item_id] = { }
                for option in options:
                    histograms_options[item_id][option] = 0
                histograms_correct[item_id] = { }

                        
            if o == 'choice_original_order':
                letter = choice_original_order
                if letter not in options:
                    continue
                histograms_options[item_id][letter] = histograms_options[item_id].get(letter, 0) + 1
                          
            elif o == 'choice_shuffled_order':
                letter = choice_shuffled_order
                histograms_options[item_id][letter] = histograms_options[item_id].get(letter, 0) + 1
            
            if choice_original_order == correct_original_order:
                    column_name = 'human_accuracy'
                    histograms_correct[item_id][column_name] = histograms_correct[item_id].get(column_name, 0) + 1
            else:
                    column_name = 'WRONG'
                    histograms_correct[item_id][column_name] = histograms_correct[item_id].get(column_name, 0) + 1    
            
    # Gabarito
    for item_id, correct_choice in enumerate(correct_response_pattern, start=1):
        correct_options.append(correct_choice)

    # Convert the histograms to a DataFrame for better presentation
    histogram_options_df = pd.DataFrame(histograms_options).sort_index()
    histogram_options_df.fillna(0, inplace=True)

    histogram_correct_df = pd.DataFrame(histograms_correct).sort_index()
    histogram_correct_df.fillna(0, inplace=True)

    # Display the resulting histogram DataFrame
    normalized_histogram_options_df = histogram_options_df/histogram_options_df.sum()
    normalized_histogram_options_df = normalized_histogram_options_df.transpose()
    normalized_histogram_options_df['human_entropy'] = normalized_histogram_options_df.apply(entropy, axis=1) # +  np.random.uniform(-0.001, 0.001, len(normalized_histogram_df['A']))  
    normalized_histogram_options_df['human_item_id'] = range(1, len(normalized_histogram_options_df) + 1)

    normalized_histogram_correct_df = histogram_correct_df/histogram_correct_df.sum()
    normalized_histogram_correct_df = normalized_histogram_correct_df.transpose()
    normalized_histogram_correct_df['human_item_id'] = range(1, len(normalized_histogram_correct_df) + 1)
   
    normalized_histogram_options_df['CORRECT_OPTION_HUMAN'] = correct_options
    histogram_df = pd.merge(normalized_histogram_options_df, normalized_histogram_correct_df, how='left', on='human_item_id')
    return pd.merge(histogram_df, itens_df, how='left', on='human_item_id')

In [15]:
import numpy as np

year = "2022"

# MT 1082
# CH 1062
# CN 1092

print('reading enem...')
enem_human_df = pd.read_csv(f"C:/Users/pedro/Downloads/TRI/microdados_enem_2022/DADOS/MICRODADOS_ENEM_{year}.csv", nrows= 7 * 1000 * 1000, sep=";",  encoding='latin') 
print('enem read.')
for exam in ['CN']:
    print('exam', exam)
    co_provas = enem_human_df['CO_PROVA_'+exam].unique()
    co_provas = [1092]
    print(co_provas)
    for co_prova in co_provas:
        if np.isnan(co_prova):
            continue
        print('co_prova', int(co_prova))
        df = generate_human_histogram_df(enem_human_df, PROVA=exam, CO_PROVA=co_prova, o='choice_original_order')
        
        df.rename(columns={'A': 'human_A', 'B': 'human_B', 'C': 'human_C', 'D': 'human_D', 'E': 'human_E' }, inplace=True)
        df.drop(columns='WRONG', inplace=True)

        
        df.to_csv(f"C:/Users/pedro/Downloads/TRI/test_responses_humans/2022/itens/human_itens_{exam}_{int(co_prova)}_{year}.csv")

        #df = generate_human_histogram_df(enem_human_df, PROVA=exam, CO_PROVA=co_prova, o='correct_percentage', normalize=True)
        #df.to_csv(f"C:/Users/pedro/Downloads/TRI/test_responses_humans/2022/correct_percentage/correct_percentage_{exam}_{int(co_prova)}.csv")

reading enem...
enem read.
exam CN
[1092]
co_prova 1092
len_itens_df 45